### ISSUE TITLE
android crash after app allow location permission 

### ISSUE THREAD

**Issue by AvitaliyaORG** [nitish24p/react-native-upi#24]
I'm trying to get the location after I allow the location permission dialog app to immediately crash. 

 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11403, result=-1, data=Intent { (has extras) }} to activity {com.waterkart/com.waterkart.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4382)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4424)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at com.upi.payment.UpiPaymentModule.onActivityResult(UpiPaymentModule.java:102)

**Comment by nitish24p** [comment]
Can you give me a reproducible link / repo for this case.. Also what SDK and RN version are you using..

**Comment by AvitaliyaORG** [comment]
"react": "16.13.1",
"react-native": "0.63.3",
 "react-native-upi-payment": "^1.0.2"
 
 Android: 
buildToolsVersion = "29.0.2"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29
 
 @nitish24p  here is my react native & SDk version
